name: focus
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_statusbarcolor: ^0.0.3
  path_provider:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  audioplayers:
    git:
      url: git://github.com/the4thfloor/audioplayer.git

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/brownnoise.png
    - assets/coffee.png
    - assets/fan.png
    - assets/fire.png
    - assets/forest.png
    - assets/leaves.png
    - assets/night.png
    - assets/pinknoise.png
    - assets/rain.png
    - assets/seaside.png
    - assets/thunder.png
    - assets/train.png
    - assets/water_pops.png
    - assets/water.png
    - assets/whitenoise.png
    - assets/wind.png
    - assets/sounds/brownnoise.mp3
    - assets/sounds/coffee.mp3
    - assets/sounds/fan.mp3
    - assets/sounds/fire.mp3
    - assets/sounds/forest.mp3
    - assets/sounds/leaves.mp3
    - assets/sounds/night.mp3
    - assets/sounds/pinknoise.mp3
    - assets/sounds/rain.mp3
    - assets/sounds/seaside.mp3
    - assets/sounds/thunder.mp3
    - assets/sounds/train.mp3
    - assets/sounds/water_pops.mp3
    - assets/sounds/water.mp3
    - assets/sounds/whitenoise.mp3
    - assets/sounds/wind.mp3
    - assets/sounds/sample_loop.wav


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Poppins
    - fonts:
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 200
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
